### PR TITLE
started python script. added gitignore

### PR DESCRIPTION
**Pull request by bdp1312**

### CODE REVIEW

**Comment by bdp1312** [comment]
my bad m8. misclicked

**Comment by magnusviri** [comment]
I made a similar [script](https://gist.github.com/magnusviri/a93b5ab02663f30eac176ca49b0250e3#file-wordle-popularity-py) this weekend. I discuss it a little [on my webpage](https://magnusviri.com/wordle.html).

**Comment by 0x6772** [comment]
@magnusviri - tried to include you on an email I just sent to @tabatkins re: sharing work, but I couldn't find an email address for you either here or on your webpage. I've fiddled around with this a bit too, and I'd very much like to collaborate, because I'm pretty sure I've missed any number of tricks. My email address (is listed on my profile here, but also:) is gr@eclipsed.net.

**Comment by tabatkins** [comment]
While I'm glad for others to use this list for their own work in writing interactive wordle solvers, I'm not myself interested in writing or collaborating on one.

**Pull request closed without merging**
